#!/usr/bin/env bash

set -euo pipefail

module_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
module_name="$(/usr/bin/ruby -rjson -e 'puts JSON.parse(File.read(ARGV.fetch(0))).fetch("module")' "$module_root/ModuleContract.json")"
simulator_arch="$(uname -m)"
translation_state="$(sysctl -in sysctl.proc_translated 2>/dev/null || true)"
if [[ "$simulator_arch" == "x86_64" && "$translation_state" == "1" ]]; then
    simulator_arch="arm64"
fi

module_directory="$module_root/.build/${simulator_arch}-apple-ios-simulator/debug/Modules"
symbol_directory="$module_root/.build/PublicAPI/SymbolGraphs"
current_report="$module_root/.build/PublicAPI/PublicAPI.md"
committed_report="$module_root/Documentation/PublicAPI.md"
ios_simulator_sdk="$(xcrun --sdk iphonesimulator --show-sdk-path)"

mkdir -p "$symbol_directory"
find "$symbol_directory" -maxdepth 1 -name '*.symbols.json' -delete
xcrun swift-symbolgraph-extract \
    -module-name "$module_name" \
    -I "$module_directory" \
    -target "${simulator_arch}-apple-ios17.0-simulator" \
    -sdk "$ios_simulator_sdk" \
    -minimum-access-level public \
    -skip-synthesized-members \
    -output-dir "$symbol_directory"

/usr/bin/ruby -rjson -e '
  module_name, symbol_directory, output = ARGV
  symbols = Dir.glob(File.join(symbol_directory, "*.symbols.json")).flat_map do |path|
    JSON.parse(File.read(path)).fetch("symbols")
  end
  rows = symbols.map do |symbol|
    kind = symbol.dig("kind", "displayName") || symbol.dig("kind", "identifier")
    declaration = symbol.fetch("declarationFragments", []).map { |fragment| fragment["spelling"] }.join
    declaration = symbol.dig("names", "title") if declaration.empty?
    [kind, declaration.gsub(/\s+/, " ").strip]
  end.uniq.sort
  File.open(output, "w") do |file|
    file.puts("# #{module_name} public API")
    file.puts
    file.puts("> Generated by `bash Scripts/generate_public_api_report.sh --update`.")
    file.puts("> Review this diff for every intentional public API change.")
    file.puts
    file.puts("| Kind | Declaration |")
    file.puts("|---|---|")
    rows.each do |kind, declaration|
      file.puts("| #{kind.gsub("|", "\\|")} | `#{declaration.gsub("`", "\\`").gsub("|", "\\|")}` |")
    end
  end
' "$module_name" "$symbol_directory" "$current_report"

if [[ "${1:-}" == "--update" ]]; then
    cp "$current_report" "$committed_report"
    echo "Updated Documentation/PublicAPI.md."
elif ! cmp -s "$current_report" "$committed_report"; then
    diff -u "$committed_report" "$current_report" || true
    echo "Public API changed. Review it and run: bash Scripts/generate_public_api_report.sh --update"
    exit 1
else
    echo "$module_name public API matches the committed report."
fi
